#!/usr/bin/perl
use strict;
use warnings;
use Cwd qw(abs_path);
use File::Basename qw(dirname);

my $real_bin = dirname(abs_path($0));
use lib;
lib->import("$real_bin/lib");

require Bmux;
Bmux->run(@ARGV);
